export interface School {
  name: string;
  slug: string;
  primary: string;
  secondary: string;
  tier: 'd1' | 'd2' | 'd3';
  /** False = colors are estimated or unverified; show manual-entry prompt */
  colorsVerified: boolean;
}

// D1 schools — official colors sourced from university brand guidelines
export const D1_SCHOOLS: School[] = [
  { name: 'Alabama Crimson Tide',          slug: 'alabama',           primary: '#9E1B32', secondary: '#828A8F', tier: 'd1', colorsVerified: true },
  { name: 'Arizona State Sun Devils',      slug: 'arizona-state',     primary: '#8C1D40', secondary: '#FFC627', tier: 'd1', colorsVerified: true },
  { name: 'Arizona Wildcats',              slug: 'arizona',           primary: '#003366', secondary: '#CC0033', tier: 'd1', colorsVerified: true },
  { name: 'Arkansas Razorbacks',           slug: 'arkansas',          primary: '#9D2235', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Auburn Tigers',                 slug: 'auburn',            primary: '#0C2340', secondary: '#E87722', tier: 'd1', colorsVerified: true },
  { name: 'Baylor Bears',                  slug: 'baylor',            primary: '#154734', secondary: '#FFB81C', tier: 'd1', colorsVerified: true },
  { name: 'Boston College Eagles',         slug: 'boston-college',    primary: '#98002E', secondary: '#BC9B6A', tier: 'd1', colorsVerified: true },
  { name: 'Cal Bears',                     slug: 'cal',               primary: '#003262', secondary: '#FDB515', tier: 'd1', colorsVerified: true },
  { name: 'Clemson Tigers',                slug: 'clemson',           primary: '#F66733', secondary: '#522D80', tier: 'd1', colorsVerified: true },
  { name: 'Colorado Buffaloes',            slug: 'colorado',          primary: '#CFB87C', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Duke Blue Devils',              slug: 'duke',              primary: '#003087', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Florida Gators',               slug: 'florida',           primary: '#0021A5', secondary: '#FA4616', tier: 'd1', colorsVerified: true },
  { name: 'Florida State Seminoles',       slug: 'florida-state',     primary: '#782F40', secondary: '#CEB888', tier: 'd1', colorsVerified: true },
  { name: 'Georgia Bulldogs',              slug: 'georgia',           primary: '#BA0C2F', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Georgia Tech Yellow Jackets',   slug: 'georgia-tech',      primary: '#B3A369', secondary: '#003057', tier: 'd1', colorsVerified: true },
  { name: 'Illinois Fighting Illini',      slug: 'illinois',          primary: '#13294B', secondary: '#E84A27', tier: 'd1', colorsVerified: true },
  { name: 'Indiana Hoosiers',              slug: 'indiana',           primary: '#990000', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Iowa Hawkeyes',                 slug: 'iowa',              primary: '#FFCD00', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Iowa State Cyclones',           slug: 'iowa-state',        primary: '#C8102E', secondary: '#F1BE48', tier: 'd1', colorsVerified: true },
  { name: 'Kansas Jayhawks',               slug: 'kansas',            primary: '#0051A5', secondary: '#E8000D', tier: 'd1', colorsVerified: true },
  { name: 'Kansas State Wildcats',         slug: 'kansas-state',      primary: '#512888', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Kentucky Wildcats',             slug: 'kentucky',          primary: '#0033A0', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'LSU Tigers',                    slug: 'lsu',               primary: '#461D7C', secondary: '#FDD023', tier: 'd1', colorsVerified: true },
  { name: 'Louisville Cardinals',          slug: 'louisville',        primary: '#AD0000', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Maryland Terrapins',            slug: 'maryland',          primary: '#E03A3E', secondary: '#FFD520', tier: 'd1', colorsVerified: true },
  { name: 'Michigan Wolverines',           slug: 'michigan',          primary: '#00274C', secondary: '#FFCB05', tier: 'd1', colorsVerified: true },
  { name: 'Michigan State Spartans',       slug: 'michigan-state',    primary: '#18453B', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Minnesota Golden Gophers',      slug: 'minnesota',         primary: '#7A0019', secondary: '#FFB71B', tier: 'd1', colorsVerified: true },
  { name: 'Mississippi State Bulldogs',    slug: 'mississippi-state', primary: '#660000', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Missouri Tigers',               slug: 'missouri',          primary: '#F1B82D', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'NC State Wolfpack',             slug: 'nc-state',          primary: '#CC0000', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Nebraska Cornhuskers',          slug: 'nebraska',          primary: '#E41C38', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'North Carolina Tar Heels',      slug: 'unc',               primary: '#4B9CD3', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Northwestern Wildcats',         slug: 'northwestern',      primary: '#4E2A84', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Notre Dame Fighting Irish',     slug: 'notre-dame',        primary: '#0C2340', secondary: '#AE9142', tier: 'd1', colorsVerified: true },
  { name: 'Ohio State Buckeyes',           slug: 'ohio-state',        primary: '#BB0000', secondary: '#666666', tier: 'd1', colorsVerified: true },
  { name: 'Oklahoma Sooners',              slug: 'oklahoma',          primary: '#841617', secondary: '#FDF9D8', tier: 'd1', colorsVerified: true },
  { name: 'Oklahoma State Cowboys',        slug: 'oklahoma-state',    primary: '#FF6600', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Ole Miss Rebels',               slug: 'ole-miss',          primary: '#CE1126', secondary: '#00205B', tier: 'd1', colorsVerified: true },
  { name: 'Oregon Ducks',                  slug: 'oregon',            primary: '#154733', secondary: '#FEE123', tier: 'd1', colorsVerified: true },
  { name: 'Oregon State Beavers',          slug: 'oregon-state',      primary: '#DC4405', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Penn State Nittany Lions',      slug: 'penn-state',        primary: '#041E42', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Pittsburgh Panthers',           slug: 'pittsburgh',        primary: '#003594', secondary: '#FFB81C', tier: 'd1', colorsVerified: true },
  { name: 'Purdue Boilermakers',           slug: 'purdue',            primary: '#CEB888', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Rutgers Scarlet Knights',       slug: 'rutgers',           primary: '#CC0033', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'South Carolina Gamecocks',      slug: 'south-carolina',    primary: '#73000A', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Stanford Cardinal',             slug: 'stanford',          primary: '#8C1515', secondary: '#B6B1A9', tier: 'd1', colorsVerified: true },
  { name: 'Syracuse Orange',               slug: 'syracuse',          primary: '#F76900', secondary: '#000E54', tier: 'd1', colorsVerified: true },
  { name: 'TCU Horned Frogs',              slug: 'tcu',               primary: '#4D1979', secondary: '#A3A9AC', tier: 'd1', colorsVerified: true },
  { name: 'Tennessee Volunteers',          slug: 'tennessee',         primary: '#FF8200', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Texas A&M Aggies',              slug: 'texas-am',          primary: '#500000', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Texas Longhorns',               slug: 'texas',             primary: '#BF5700', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Texas Tech Red Raiders',        slug: 'texas-tech',        primary: '#CC0000', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'UCLA Bruins',                   slug: 'ucla',              primary: '#2D68C4', secondary: '#F2A900', tier: 'd1', colorsVerified: true },
  { name: 'USC Trojans',                   slug: 'usc',               primary: '#990000', secondary: '#FFC72C', tier: 'd1', colorsVerified: true },
  { name: 'Utah Utes',                     slug: 'utah',              primary: '#CC0000', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Vanderbilt Commodores',         slug: 'vanderbilt',        primary: '#866D4B', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Virginia Cavaliers',            slug: 'virginia',          primary: '#232D4B', secondary: '#E57200', tier: 'd1', colorsVerified: true },
  { name: 'Virginia Tech Hokies',          slug: 'virginia-tech',     primary: '#75091D', secondary: '#CF4420', tier: 'd1', colorsVerified: true },
  { name: 'Wake Forest Demon Deacons',     slug: 'wake-forest',       primary: '#9E7E38', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Washington Huskies',            slug: 'washington',        primary: '#33006F', secondary: '#E8D3A2', tier: 'd1', colorsVerified: true },
  { name: 'Washington State Cougars',      slug: 'washington-state',  primary: '#981E32', secondary: '#5E6A71', tier: 'd1', colorsVerified: true },
  { name: 'Wisconsin Badgers',             slug: 'wisconsin',         primary: '#C5050C', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  // Additional D1 programs
  { name: 'BYU Cougars',                   slug: 'byu',               primary: '#002E5D', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Cincinnati Bearcats',           slug: 'cincinnati',        primary: '#E00122', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'Colorado State Rams',           slug: 'colorado-state',    primary: '#1E4D2B', secondary: '#C8C372', tier: 'd1', colorsVerified: true },
  { name: 'Connecticut Huskies',           slug: 'uconn',             primary: '#000E2F', secondary: '#E4002B', tier: 'd1', colorsVerified: true },
  { name: 'Dayton Flyers',                 slug: 'dayton',            primary: '#CE1141', secondary: '#0A1942', tier: 'd1', colorsVerified: true },
  { name: 'DePaul Blue Demons',            slug: 'depaul',            primary: '#005587', secondary: '#E4002B', tier: 'd1', colorsVerified: true },
  { name: 'Georgetown Hoyas',              slug: 'georgetown',        primary: '#041E42', secondary: '#8D817B', tier: 'd1', colorsVerified: true },
  { name: 'Gonzaga Bulldogs',              slug: 'gonzaga',           primary: '#002469', secondary: '#CC0000', tier: 'd1', colorsVerified: true },
  { name: 'Hawaii Warriors',               slug: 'hawaii',            primary: '#024731', secondary: '#C8AA76', tier: 'd1', colorsVerified: true },
  { name: 'Houston Cougars',               slug: 'houston',           primary: '#C8102E', secondary: '#63666A', tier: 'd1', colorsVerified: true },
  { name: 'Marquette Golden Eagles',       slug: 'marquette',         primary: '#003366', secondary: '#FFCC00', tier: 'd1', colorsVerified: true },
  { name: 'Memphis Tigers',                slug: 'memphis',           primary: '#003087', secondary: '#898D8D', tier: 'd1', colorsVerified: true },
  { name: 'Miami Hurricanes',              slug: 'miami',             primary: '#005030', secondary: '#F47321', tier: 'd1', colorsVerified: true },
  { name: 'Providence Friars',             slug: 'providence',        primary: '#002147', secondary: '#75B2DD', tier: 'd1', colorsVerified: true },
  { name: 'Saint Louis Billikens',         slug: 'saint-louis',       primary: '#003DA5', secondary: '#9EA2A2', tier: 'd1', colorsVerified: true },
  { name: 'San Diego State Aztecs',        slug: 'sdsu',              primary: '#A6192E', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'SMU Mustangs',                  slug: 'smu',               primary: '#354CA1', secondary: '#CC0035', tier: 'd1', colorsVerified: true },
  { name: 'UC Santa Barbara Gauchos',      slug: 'ucsb',              primary: '#003660', secondary: '#FEBC11', tier: 'd1', colorsVerified: true },
  { name: 'UNLV Runnin\' Rebels',          slug: 'unlv',              primary: '#CE1141', secondary: '#808080', tier: 'd1', colorsVerified: true },
  { name: 'Villanova Wildcats',            slug: 'villanova',         primary: '#00205B', secondary: '#009BDE', tier: 'd1', colorsVerified: true },
  { name: 'Xavier Musketeers',             slug: 'xavier',            primary: '#002651', secondary: '#9E9C99', tier: 'd1', colorsVerified: true },
  { name: 'University of Portland Pilots', slug: 'portland',          primary: '#4B2E83', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Pepperdine Waves',              slug: 'pepperdine',        primary: '#0C3B8C', secondary: '#FF7300', tier: 'd1', colorsVerified: true },
  { name: 'Santa Clara Broncos',           slug: 'santa-clara',       primary: '#862633', secondary: '#FFFFFF', tier: 'd1', colorsVerified: true },
  { name: 'Loyola Marymount Lions',        slug: 'lmu',               primary: '#00205B', secondary: '#69B3E7', tier: 'd1', colorsVerified: true },
  { name: 'San Francisco Dons',            slug: 'usf',               primary: '#004B87', secondary: '#CBA135', tier: 'd1', colorsVerified: true },
  { name: 'Pacific Tigers',                slug: 'pacific',           primary: '#F05523', secondary: '#000000', tier: 'd1', colorsVerified: true },
  { name: 'St. Mary\'s Gaels',             slug: 'saint-marys',       primary: '#013A81', secondary: '#BC151A', tier: 'd1', colorsVerified: true },
  { name: 'Fresno State Bulldogs',         slug: 'fresno-state',      primary: '#CC0033', secondary: '#002244', tier: 'd1', colorsVerified: true },
  { name: 'UC Davis Aggies',               slug: 'uc-davis',          primary: '#002855', secondary: '#B3A369', tier: 'd1', colorsVerified: true },
  { name: 'UC Irvine Anteaters',           slug: 'uc-irvine',         primary: '#0064A4', secondary: '#FFD200', tier: 'd1', colorsVerified: true },
  { name: 'Utah State Aggies',             slug: 'utah-state',        primary: '#003263', secondary: '#8A8D8F', tier: 'd1', colorsVerified: true },
  { name: 'Boise State Broncos',           slug: 'boise-state',       primary: '#D64309', secondary: '#0033A0', tier: 'd1', colorsVerified: true },
  { name: 'New Mexico Lobos',              slug: 'new-mexico',        primary: '#BA0C2F', secondary: '#63666A', tier: 'd1', colorsVerified: true },
  { name: 'Wyoming Cowboys',               slug: 'wyoming',           primary: '#492F24', secondary: '#FFC425', tier: 'd1', colorsVerified: true },
  { name: 'Air Force Falcons',             slug: 'air-force',         primary: '#003087', secondary: '#8A8D8F', tier: 'd1', colorsVerified: true },
  { name: 'Army Black Knights',            slug: 'army',              primary: '#000000', secondary: '#D4B483', tier: 'd1', colorsVerified: true },
  { name: 'Navy Midshipmen',               slug: 'navy',              primary: '#00205B', secondary: '#B3A369', tier: 'd1', colorsVerified: true },
];

// D2 schools — major programs with verifiable colors
export const D2_SCHOOLS: School[] = [
  { name: 'Adelphi Panthers',              slug: 'adelphi',           primary: '#7B0D1E', secondary: '#D4AF37', tier: 'd2', colorsVerified: true },
  { name: 'Barry Buccaneers',              slug: 'barry',             primary: '#C41230', secondary: '#000000', tier: 'd2', colorsVerified: true },
  { name: 'Bellarmine Knights',            slug: 'bellarmine',        primary: '#C8102E', secondary: '#000000', tier: 'd2', colorsVerified: true },
  { name: 'Cal Poly Pomona Broncos',       slug: 'cal-poly-pomona',   primary: '#006633', secondary: '#FFD700', tier: 'd2', colorsVerified: true },
  { name: 'California Baptist Lancers',    slug: 'cal-baptist',       primary: '#003087', secondary: '#FFCC00', tier: 'd2', colorsVerified: true },
  { name: 'Carson-Newman Eagles',          slug: 'carson-newman',     primary: '#F77F00', secondary: '#003087', tier: 'd2', colorsVerified: true },
  { name: 'Chico State Wildcats',          slug: 'chico-state',       primary: '#CC0000', secondary: '#FFFFFF', tier: 'd2', colorsVerified: true },
  { name: 'Colorado Mesa Mavericks',       slug: 'colorado-mesa',     primary: '#003366', secondary: '#FFC72C', tier: 'd2', colorsVerified: true },
  { name: 'Concordia-Irvine Eagles',       slug: 'concordia-irvine',  primary: '#002A5C', secondary: '#F7A11A', tier: 'd2', colorsVerified: true },
  { name: 'Dominican University of CA',    slug: 'dominican-ca',      primary: '#003087', secondary: '#C8A951', tier: 'd2', colorsVerified: true },
  { name: 'Drury Panthers',                slug: 'drury',             primary: '#003087', secondary: '#C41230', tier: 'd2', colorsVerified: true },
  { name: 'Embry-Riddle Eagles',           slug: 'embry-riddle',      primary: '#003087', secondary: '#FFCC00', tier: 'd2', colorsVerified: true },
  { name: 'Flagler Saints',                slug: 'flagler',           primary: '#C8102E', secondary: '#000000', tier: 'd2', colorsVerified: true },
  { name: 'Florida Southern Moccasins',    slug: 'florida-southern',  primary: '#003087', secondary: '#A80000', tier: 'd2', colorsVerified: true },
  { name: 'Grand Canyon Antelopes',        slug: 'grand-canyon',      primary: '#522398', secondary: '#A57C2A', tier: 'd2', colorsVerified: true },
  { name: 'Humboldt State Lumberjacks',    slug: 'humboldt',          primary: '#006633', secondary: '#FFD700', tier: 'd2', colorsVerified: true },
  { name: 'Lynn Fighting Knights',         slug: 'lynn',              primary: '#003087', secondary: '#FFCC00', tier: 'd2', colorsVerified: true },
  { name: 'Nova Southeastern Sharks',      slug: 'nova-southeastern', primary: '#003087', secondary: '#6CB4E4', tier: 'd2', colorsVerified: true },
  { name: 'Rollins Tars',                  slug: 'rollins',           primary: '#003087', secondary: '#C8A951', tier: 'd2', colorsVerified: true },
  { name: 'Saint Leo Lions',               slug: 'saint-leo',         primary: '#660099', secondary: '#FFCC00', tier: 'd2', colorsVerified: true },
  { name: 'Tampa Spartans',                slug: 'tampa',             primary: '#990000', secondary: '#C8A951', tier: 'd2', colorsVerified: true },
  { name: 'UC San Diego Tritons',          slug: 'ucsd',              primary: '#00629B', secondary: '#FFD700', tier: 'd2', colorsVerified: true },
  { name: 'West Florida Argonauts',        slug: 'west-florida',      primary: '#003087', secondary: '#C8A951', tier: 'd2', colorsVerified: true },
  { name: 'Western Washington Vikings',    slug: 'western-washington', primary: '#003087', secondary: '#C41230', tier: 'd2', colorsVerified: true },
  { name: 'Wingate Bulldogs',              slug: 'wingate',           primary: '#003087', secondary: '#C8A951', tier: 'd2', colorsVerified: true },
];

// D3 schools — major programs with verifiable colors
export const D3_SCHOOLS: School[] = [
  { name: 'Amherst Mammoths',              slug: 'amherst',           primary: '#3F1F69', secondary: '#FFFFFF', tier: 'd3', colorsVerified: true },
  { name: 'Bowdoin Polar Bears',           slug: 'bowdoin',           primary: '#000000', secondary: '#FFFFFF', tier: 'd3', colorsVerified: true },
  { name: 'Bates Bobcats',                 slug: 'bates',             primary: '#860038', secondary: '#FFFFFF', tier: 'd3', colorsVerified: true },
  { name: 'Brandeis Judges',               slug: 'brandeis',          primary: '#003478', secondary: '#FFFFFF', tier: 'd3', colorsVerified: true },
  { name: 'Carnegie Mellon Tartans',       slug: 'carnegie-mellon',   primary: '#C41230', secondary: '#3D3D3D', tier: 'd3', colorsVerified: true },
  { name: 'Case Western Spartans',         slug: 'case-western',      primary: '#003B71', secondary: '#6CACE4', tier: 'd3', colorsVerified: true },
  { name: 'Claremont-Mudd-Scripps Stags',  slug: 'cms',               primary: '#7C2529', secondary: '#CCCCCC', tier: 'd3', colorsVerified: true },
  { name: 'Colby White Mules',             slug: 'colby',             primary: '#003366', secondary: '#C0C0C0', tier: 'd3', colorsVerified: true },
  { name: 'Emory Eagles',                  slug: 'emory',             primary: '#012169', secondary: '#F2A900', tier: 'd3', colorsVerified: true },
  { name: 'Haverford Fords',               slug: 'haverford',         primary: '#003087', secondary: '#FFFFFF', tier: 'd3', colorsVerified: true },
  { name: 'Johns Hopkins Blue Jays',       slug: 'johns-hopkins',     primary: '#002D72', secondary: '#68ACE5', tier: 'd3', colorsVerified: true },
  { name: 'Kenyon Lords',                  slug: 'kenyon',            primary: '#4A154B', secondary: '#C8A951', tier: 'd3', colorsVerified: true },
  { name: 'Middlebury Panthers',           slug: 'middlebury',        primary: '#003087', secondary: '#FFFFFF', tier: 'd3', colorsVerified: true },
  { name: 'MIT Engineers',                 slug: 'mit',               primary: '#8A0000', secondary: '#C2C0BF', tier: 'd3', colorsVerified: true },
  { name: 'Pomona-Pitzer Sagehens',        slug: 'pomona-pitzer',     primary: '#003087', secondary: '#FECC00', tier: 'd3', colorsVerified: true },
  { name: 'Swarthmore Garnet',             slug: 'swarthmore',        primary: '#8B0000', secondary: '#FFFFFF', tier: 'd3', colorsVerified: true },
  { name: 'Trinity Bantams',               slug: 'trinity-ct',        primary: '#003087', secondary: '#C8A951', tier: 'd3', colorsVerified: true },
  { name: 'Tufts Jumbos',                  slug: 'tufts',             primary: '#3E8EDE', secondary: '#4B306A', tier: 'd3', colorsVerified: true },
  { name: 'UC Santa Cruz Banana Slugs',    slug: 'uc-santa-cruz',     primary: '#003C6C', secondary: '#FDC700', tier: 'd3', colorsVerified: true },
  { name: 'University of Chicago Maroons', slug: 'uchicago',          primary: '#800000', secondary: '#BDBEC0', tier: 'd3', colorsVerified: true },
  { name: 'Washington and Lee Generals',   slug: 'wlu',               primary: '#003087', secondary: '#C41230', tier: 'd3', colorsVerified: true },
  { name: 'Washington University Bears',   slug: 'washu',             primary: '#990000', secondary: '#BFBFBF', tier: 'd3', colorsVerified: true },
  { name: 'Wesleyan Cardinals',            slug: 'wesleyan',          primary: '#C41230', secondary: '#000000', tier: 'd3', colorsVerified: true },
  { name: 'Williams Ephs',                 slug: 'williams',          primary: '#512698', secondary: '#FFD700', tier: 'd3', colorsVerified: true },
];

export const ALL_SCHOOLS: School[] = [...D1_SCHOOLS, ...D2_SCHOOLS, ...D3_SCHOOLS];

export const SUGGEST_CORRECTION_URL =
  'mailto:support@onepointslam.com?subject=School%20Color%20Correction&body=School%20name%3A%0APrimary%20color%20(hex)%3A%0ASecondary%20color%20(hex)%3A%0ASource%3A';
